### ISSUE TITLE
Your website is down...

### ISSUE THREAD

**Issue by Crilum** [locness3/locness3#1]
FYI, I just tried to go to your [website](https://librosphere.org/locness3), and it gave me `404`.

**Comment by moeenio** [comment]
Thank you for informing me, however I do not manage this website, it's a Pleroma (federated social networking server) node run by people I don't personally know.

It's already been down for a few days, but I believe an admin said that they won't be able to fix it until this Sunday.

**Comment by Crilum** [comment]
Well, I guess this can be closed whenever it goes back up.

**Comment by moeenio** [comment]
Closing as the website is back up.

**Comment by Crilum** [comment]
On [Min](https://minbrowser.org) (chrome) I get 404, and Firefox says it can't connect because there is a 'Potential Security Threat', a bad certificate...

Just so you know.

**Comment by moeenio** [comment]
No issues for me. You might contact the website's administrators: the relevant Matrix room is `#librosphere:helianthine.solar`, however it is French-speaking but you could send a DM to Julia. I do not know of any other way to contact them.

**Comment by moeenio** [comment]
@Crilum would you believe the url was wrong? lol that was the issue, it's librosphere.fr not librosphere.org

**Comment by Crilum** [comment]
Oh, yeah. https://librosphere.fr/locness3 works!
